# Build upon this image "alpine" is a lightweight distro
FROM python:3.9.13-alpine3.15 as build-stage

WORKDIR /install
# Install all the requirements
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_CACHE_DIR=1
RUN pip install --prefix=/install redis rq ffmpeg-python minio

# Stage 2
FROM python:3.9.12-alpine3.15 as production-stage

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache --update --virtual build-dependencies ffmpeg imagemagick
COPY --from=build-stage /install /usr/local
RUN rm -rf /install

# Copy everthing from . to /app inside the 'box'

COPY web-controller/worker_extract.py /app/worker.py
COPY web-controller/web_controller/utils/worker_utility.py /app/web_controller/utils/worker_utility.py
COPY web-controller/web_controller/utils/__init__.py /app/web_controller/utils/__init__.py
COPY web-controller/web_controller/utils/compose_worker.py /app/web_controller/utils/compose_worker.py
COPY web-controller/web_controller/utils/extract_worker.py /app/web_controller/utils/extract_worker.py
COPY web-controller/web_controller/utils/minio_update.py /app/web_controller/utils/minio_update.py
COPY script/src/ /script/src/
WORKDIR /app

# How to run it when we start up the box?
ENTRYPOINT ["python", "worker.py"]

# ENV FLASK_APP=main
# CMD ["flask", "run", "--host", "0.0.0.0"]