# minio service
kind: Service
apiVersion: v1
metadata:
  name: p2-minio
spec:
  selector:
    app: p2-minio
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2-pv-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-minio
spec:
  selector:
    matchLabels:
      app: p2-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2-minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        args:
        - server
        - /storage
        env:
        # Change this to secret
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: p2-minio-secret
              key: username
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: p2-minio-secret
              key: password
        ports:
        - containerPort: 9000
          hostPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: p2-vc
          mountPath: "/storage"
      volumes:
      - name: p2-vc
        persistentVolumeClaim:
          claimName: p2-pv-claim