# minio service
kind: Service
apiVersion: v1
metadata:
  name: p2-object-store
spec:
  selector:
    app: p2-object-store
  ports:
  - protocol: TCP
    port: 80
    # targetPort: 5000 idk yet
---
# Tenant Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: direct-csi-min-io
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# Tenant Persistent Volumes
