version: '3'
services:
  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
  extract-and-resize-worker:
    build:
      context: workers/extract-and-resize
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
  gif-composer-worker:
    build:
      context: workers/gif-composer
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
  queue-wrapper:
    build:
      context: queue-wrapper
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'