name: Build Web Controller CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}

jobs:
  build-web-controller:
    runs-on: ['lol']
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log in to registry
      uses: docker/login-action@v2 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Derive short SHA name
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build image
      run: |
        cd web-controller && docker build . --file Dockerfile --no-cache \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/p2-web-controller:${{ steps.vars.outputs.sha_short }} \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/p2-web-controller:latest
    - name: Publish the image
      run: |
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/p2-web-controller:${{ steps.vars.outputs.sha_short }}
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/p2-web-controller:latest